### ISSUE TITLE
provider_hart_package - missing closed bracket at the end of line 58

### ISSUE THREAD

**Issue by chrisduong** [chef-cookbooks/habitat#1]
Hi,

Just a small syntax error.

**Comment by smith** [comment]
Sorry, I'm not seeing where this is. Could you please provide a link to the specific line and commit?

**Comment by chrisduong** [comment]
Hi, 

I'm sorry, it fails with `provider_hart_package`. I changed the title to reflect it.

Here is the log from Travis.

> 
0.29s$ /opt/chefdk/embedded/bin/foodcritic --version
foodcritic 7.0.1
51.79s$ KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
-----> Starting Kitchen (v1.10.2)
-----> Creating <default-ubuntu-1204>...
       Finished creating <default-ubuntu-1204> (0m44.26s).
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.5...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-ubuntu-1204>
Starting Chef Client, version 12.12.13
Creating a new client identity for default-ubuntu-1204 using the validator key.
resolving cookbooks for run list: ["habitat::default"]
Synchronizing Cookbooks:
  - habitat (0.0.3)
Installing Cookbook Gems:
Compiling Cookbooks...
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/habitat/libraries/provider_hart_package.rb
================================================================================
SyntaxError
-----------
/opt/kitchen/cache/cookbooks/habitat/libraries/provider_hart_package.rb:59: syntax error, unexpected keyword_end, expecting ')'
Platform:
---------
x86_64-linux
Running handlers:
[2016-07-19T07:43:56+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-19T07:43:56+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2016-07-19T07:43:56+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2016-07-19T07:43:56+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-19T07:43:56+00:00] ERROR: /opt/kitchen/cache/cookbooks/habitat/libraries/provider_hart_package.rb:59: syntax error, unexpected keyword_end, expecting ')'
[2016-07-19T07:43:57+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
