### ISSUE TITLE
hab svc load fails on SLES 12.3

### ISSUE THREAD

**Issue by srb3** [chef-cookbooks/habitat#107]
This is sort of a bug and also sort of the fault of SLES default configuration 

### Cookbook version
0.56.1

### Chef-client version
13.8.3 

### Platform Details
SLES 12 sp 3

### Scenario:
install hab supervisor and load a service

### Steps to Reproduce:
Start a aws sles 12.3 instance run a cookbook that uses the habitat cookbook to:
```
hab_install 'install habitat'
hab_sup 'default'
hab_service <my_origin/my_package> do
  service_group node.chef_environment
  channel node['hab']['channel']
  strategy node['hab']['strategy']
end
```
run it in chef-solo
### Expected Result:
habitat is installed and the supervisor is started and the service is loaded into the supervisor

### Actual Result:
```
Jun 26 14:48:53 ip-10-166-24-103 hab[30734]: hab-sup(AG): The binpath/sample-node-app service was successfully loaded
Jun 26 14:48:55 ip-10-166-24-103 hab[30734]: hab-sup(MR): Starting binpath/sample-node-app
Jun 26 14:48:55 ip-10-166-24-103 hab[30734]: hab-sup(MR): Can't create directory /hab/svc/sample-node-app: hab-sup(UR)[components/sup/src/sys/u
Jun 26 14:48:55 ip-10-166-24-103 hab[30734]: hab-sup(MR): If this service is running as non-root, you'll need to create /hab/svc/sample-node-ap
Jun 26 14:48:55 ip-10-166-24-103 hab[30734]: hab-sup(MR): binpath/sample-node-app failed to start
```

the reason it fails is because on SUSE linux the useradd command is overridden to not create a user group automatically. So only the user `hab` is created and it does not get the group `hab` assigned to it 

man page for useradd:
```
If not specified, the behavior of useradd will depend on the USERGROUPS_ENAB variable in /etc/login.defs. If this variable is set to yes (or -U/--user-group
           is specified on the command line), a group will be created for the user, with the same name as her loginname. If the variable is set to no (or
           -N/--no-user-group is specified on the command line), useradd will set the primary group of the new user to the value specified by the GROUP variable in
           /etc/default/useradd, or 100 by default.
```

login.defs on a default sles 12.3 install

```
ip-172-31-37-216:~ # grep USERGROUPS_ENAB  /etc/login.defs
USERGROUPS_ENAB no
```

login.defs on a default redhat 7.5 install
```
[root@ip-172-31-34-95 ~]# grep USERGROUPS_ENAB /etc/login.defs
USERGROUPS_ENAB yes
```

the code in the resource for install creates a hab user
https://github.com/chef-cookbooks/habitat/blob/master/resources/install.rb#L33-L37
it uses the user chef resource to create the hab user which shells out to `useradd`

 and on most systems like redhat this works fine, as the useradd command behaves with the default setting and creates a user group for hab. On SUSE Linux this does not happen and services fail to load as the hab user cannot create the `/hab/svc/<service_name>` directory

**Comment by jonlives** [comment]
Just checking in to see if this issue has now been resolved after the new release :)

**Comment by sam1el** [comment]
no response in 2 years. I will test this myself. if resolved will be closing.
