### ISSUE TITLE
Wrong hab_service.service_name property

### ISSUE THREAD

**Issue by jsirex** [chef-cookbooks/habitat#116]
Hello!

I faced an issue which I can't understand how to fix without rewriting the habitat cookbook.
My use case is pretty simple: **I want to run a service**.

```ruby
hab_install
hab_sup 'default'

hab_service 'core/postgresql/9.6.8'
```

I see in the source wrong "service_name" property, but actually it **must** be **PKG_IDENT**.
Actual result cookbook unable to detect service and tries load already loaded service.

We **must** give ability to specify exact version of service I want to run.
The following code will not work as expected:

```ruby
...
# Installing 9.6.8
hab_package 'core/postgresql/9.6.8'
# Starting service, but there is 9.6.9 already released, so 9.6.9 will have been started
hab_service 'core/postgresql'
```

**Comment by jonlives** [comment]
Is the issue here that you have two version of a package installed and are trying to run the older one? Or is your hab_package resource not installing the correct version? If so, you might want to try passing the "9.6.8" part as the "version" attribute instead of in the resource name.

**Comment by jsirex** [comment]
I see tons of issues there because of naming and conventions. It is not clear which package will be used on which circumstances.
It is better to be more specific, so I'll file number of issues.
Unfortunately this cookbook is too buggy now and can be used for production ;(

**Comment by jonlives** [comment]
I'm taking on maintenance of this cookbook going forwards so I'd definitely welcome those issue reports about what's not working for you - it may also point to improvements we can make in our testing suite.
