### ISSUE TITLE
Binlink when installing a package with hab_package resource?

### ISSUE THREAD

**Issue by qubitrenegade** [chef-cookbooks/habitat#138]
### Cookbook version
0.63.0

### Chef-client version
Any

### Platform Details
Linux is all I care about, but could probably apply to Windows too.

### Scenario:
Binlink a hab package on install.

### Steps to Reproduce:
Currently we're:

```
  hab_package 'hab package install' do
    package_name 'core/terraform'
    action :install
  end
  execute 'binlink' do
    command 'hab pkg binlink core/terraform'
    user 'root'
  end
```
Which seems a bit kludgely...

### Expected Result:
I would like to be able to binlink without an `execute` resource, e.g.:

```
  hab_package 'hab package install' do
    package_name 'core/terraform'
    # same as --binlink
    binlink: true
    # same as --binlink --force
    # binlink: :force
    # default
    # binlink: false
    action :install
  end
```

### Actual Result:
[As far as I can tell](https://github.com/chef-cookbooks/habitat/blob/master/libraries/provider_hab_package.rb#L68-L72) there's currently no way to binlink when you install.

I'd be happy to make the change and submit a PR if this is a feature that we think would be valuable?

Thanks!
-Q

**Comment by jonlives** [comment]
I'd be happy to look at a PR for that feature, I can see it being really useful! 👍
