### ISSUE TITLE
a running service which is not configured correctly is not fixed by a chef-client run

### ISSUE THREAD

**Issue by st-h** [chef-cookbooks/habitat#141]
### Cookbook version
0.63.0

### Chef-client version
14.3.37

### Platform Details
ubuntu 16.04

### Scenario:
As described in this [post](https://forums.habitat.sh/t/how-to-debug-supervisor-which-does-not-update-a-certain-package-to-its-latest-version/868) over at the habitat forum, I noticed that one package on a node would not update to the latest available version. After enabling debug logging it turned out that the service is not started with the update strategy specified in the corresponding recipe:
```
hab_service 'myorg/mypkg-core' do
  action :load
  strategy 'at-once'
  channel node.habitat['channel']
end
```
It seems like for some unknown reason the package has lost its initially configured update strategy or the configuration probably has been changed over the lifespan of that node. There does not seem to be any means implemented which would check if a service is actually running in the desired state.

### Expected Result:
This cookbook should probably notice when a service is configured incorrectly / or when a change of configuration occurs after initial setup. The service should most likely be restarted with the updated configuration.

### Actual Result:
cookbook does not correct any mismatches in configuration

If we can agree on how to implement this, I'll be happy to help getting this done. I'm no chef expert, so a little help would be much appreciated.

**Comment by sam1el** [comment]
issue appears to be resolved as of recent work, closing
