### ISSUE TITLE
Instead of raising, install habitat

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/habitat#17]
https://github.com/chef-cookbooks/habitat/pull/11#discussion_r86643756

Instead of raising, let's install habitat. Obviously the user wants to use it if they're saying `hab_package`, right?

**Comment by lamont-granquist** [comment]
that feels a bit like excessive magic?

**Comment by jtimberman** [comment]
I'm not strongly attached to doing this, just opening the issue based on @tas50's comment that I linked from PR #11. I'll let him weigh in on this.

**Comment by lamont-granquist** [comment]
better addressed through a PR if someone feels strongly
