### ISSUE TITLE
Supervisor continuously restarting on windows

### ISSUE THREAD

**Issue by devoptimist** [chef-cookbooks/habitat#178]
### Cookbook version
0.83.0

### Chef-client version
15 and 14

### Platform Details
Windows Server 2016

### Scenario:
The supervisor is restarting on every chef run. The restart is triggered by installing hab-launcher on every chef run. the hab package windows-service has a tdep on hab-launcher 9106 

```
PS C:\hab\pkgs\core\windows-service\0.3.1\20181204233941> cat .\TDEPS
core/hab-launcher/9106/20181126170957
core/powershell/6.1.0/20181102163441
```
The habitat cookbook sets the hab luncher constant to 8656 for 0.3.1 
```
    WINDOWS_LAUNCHER_VERSION = '8656'.freeze
    WINDOWS_SERVICE_VERSION = '0.3.1'.freeze
```

I think this is causing the package version check to become confused.
it uses hab pkg path to check the current version
```
hab('pkg', 'path', ident).stdout.chomp.split(platform_family?('windows') ? '\\' : '/')[-2..-1].join('/')
```
hab pkg path seems to return the latest installed packages path if called without a version and release number.

So on every chef run the chef-client checks to see if it should install hab-launcher v8656 and sees it does not have it installed only version v9106 and reinstalls v8656 (which is already installed) and this triggers the notify to restart the supervisor.

The easy fix is to update the WINDOWS_LAUNCHER_VERSION or more tightly fix the WINDOWS_SERVICE_VERSION.

Or make the provider aware of all the versions of a package that are installed.

**Comment by jonlives** [comment]
Closing as associated PR merged and released.
