### ISSUE TITLE
sup systemd provider should expose setting file limit

### ISSUE THREAD

**Issue by devoptimist** [chef-cookbooks/habitat#180]
### Cookbook version
0.83

### Chef-client version
15

### Platform Details
all linux systemd platforms

### Scenario:
Some habitat services require increasing the limit of the number of open files allowed by the user running the service.
Elasticsearch is a common example of this.

```
Elasticsearch uses a lot of file descriptors or file handles. Running out of file descriptors can be disastrous and will most probably lead to data loss. Make sure to increase the limit on the number of open file descriptors for the user running Elasticsearch to 65,536 or higher.

For the .zip and .tar.gz packages, set ulimit -n 65535 as root before starting Elasticsearch, or set nofile to 65535 in /etc/security/limits.conf.
```
 (https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html)

normally this would be set in `/etc/security/limits.conf` or via the command line.
However, systemd intentionally ignores the settings from the limits.conf.
When running a habitat elasticsearch instance the limit on the number of open files is set from the supervisors systemd unit file (or if no limit is set in the unit file it inherits a global default 4096)

From what I can work out the correct way to alter the limit on the number of open files in systemd is to specify it in the unit file for a service, or globally in /etc/systemd/system.conf

unit file
```
[Unit]
Description = The Habitat Supervisor

[Service]
LimitNOFILE = 65536
ExecStart = /bin/hab sup run
```
/etc/systemd/system.conf
```
[Manager]
DefaultLimitNOFILE=65536
```

### Steps to Reproduce:
use the habitat cookbook to install hab, start the supervisor and load core/elasticsearch

### Expected Result:
The habitat cookbook allows setting of the open file limit for the habitat supervisor

```
hab_sup 'setup_supervisor' do
  license 'accept'
  limit_no_files '65536'
end
```
### Actual Result:
```
ip-10-0-1-42:~ # systemctl show hab-sup --property=LimitNOFILE
LimitNOFILE=4096
```

**Comment by jonlives** [comment]
Closing as associated PR merged and released.
