### ISSUE TITLE
platform_target method is fairly broken

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/habitat#188]
The platform_target method at https://github.com/chef-cookbooks/habitat/blob/master/libraries/provider_hab_package.rb#L112 has some issues:

1) centos isn't a platform_family
2) suse < 6 isn't correct.

**Comment by lamont-granquist** [comment]
using `#to_f` also only accidentally works because the comparison is to `< 6.0` which avoids the `6.10 == 6.1` problem.  if its gonna be YOLO-checking it should be `#to_i`'d just so that nobody copypasta's this bad code and introduces the bug.

**Comment by tas50** [comment]
This is partially fixed with https://github.com/chef-cookbooks/habitat/pull/189

**Comment by sam1el** [comment]
Altered this to correctly look for kernel release rather than platform to account for the sprawl in Distro version vs Kernel in that distro.
