### ISSUE TITLE
Add Windows platform testing for CI pipeline

### ISSUE THREAD

**Issue by emachnic** [chef-cookbooks/habitat#193]
Currently, there are no tests against Windows in the CI pipeline and so it's causing the issue where a version that works on *NIX can go out but it has broken on Windows. This is likely the case with #191. This issue is to track adding Windows as part of the CI pipeline, maybe utilizing Appveyor.

**Comment by sam1el** [comment]
I am currently working on this. As of right now, all windows functions should be working as expected. I am looking at getting these handled by github actions.

**Comment by sam1el** [comment]
This task has been completed, we will also develop new tests as needed
