### ISSUE TITLE
environment has to be explicitly set if you are customizing `unit_content`

### ISSUE THREAD

**Issue by bdangit** [chef-cookbooks/habitat#21]
for `hab_service`, I find that you have to explicitly set the environment inside the `unit_content` parameter, even though it is being set here: https://github.com/chef-cookbooks/habitat/blob/master/libraries/resource_hab_service_systemd.rb#L28

And when you do set it explicitly, I'm having a hard time trying to `shellout` the parameter that is required by this chef resource. I can't shellout the `$(hab ...)` stuff until after `hab` has been installed.

I could try doing `lazy` of the entire `unit_content` attribute.

**Comment by lamont-granquist** [comment]
Is this just a question on how to properly use lazy with a hash value?  Its true that you have to do this:

```ruby
environment( lazy {
  "stuff" => shell_out("whatever").stdout,
  "otherstuff" => "whatever",
})
```

if you try to do this:

```ruby
environment({
   "stuff" => lazy { shell_out("whatever").stdout },
  "otherstuff" => "whatever",
})
```

you'll wind up with some garbage about a DelayedEvaluator object in the hash, which is just how ruby parses things and isn't fixable.

So I think you've got how to do it correctly here:

> I could try doing lazy of the entire unit_content attribute.

**Comment by bdangit** [comment]
thanks @lamont-granquist!  I was able to get this worked out.

https://github.com/bdangit/chef-depot/blob/master/recipes/service.rb#L31-L46 where I did the first method you shared.

Even though I fixed my SSL issue, I think this part of the [README.md](https://github.com/chef-cookbooks/habitat#properties-2) could be made clearer.

**Comment by lamont-granquist** [comment]
not really a bug here
