### ISSUE TITLE
Windows Hab Service dll config needs updating

### ISSUE THREAD

**Issue by danielcbright** [chef-cookbooks/habitat#212]
It looks like the Windows Service is using a very old method of setting the launcher arguments and needs to be updated. I'm working on this, just wanted to create an issue for tracking.

**Comment by sam1el** [comment]
I wonder if this could be linked to some of the issues we're seeing with restarting the service currently. thanks for working on it

**Comment by sam1el** [comment]
@danielcbright, this is installing the windows-service from the public builder, if you can share an example of what needs to be changed for the DLL-config. I will get it in with the next release

**Comment by sam1el** [comment]
This should be resolved. Please confirm if you can @danielcbright

**Comment by sam1el** [comment]
This work has been completed
