### ISSUE TITLE
Cookbook fails if Habitat Supervisor API fails or is unavailable

### ISSUE THREAD

**Issue by ericcalabretta** [chef-cookbooks/habitat#227]
This cookbook requires the Habitat CLI and Habitat Supervisor to function correctly. 

The Habitat Supervisor may be unavailable like in a situation where security policy prevents access to port :9631 or if the API itself crashes. 

The cookbook should handle these failures by exposing a meaningful error message.

**Comment by sam1el** [comment]
I would expect that of the cookbook or even manual habitat operations. Can you give some examples? also, if port:9631 isn't available the cookbook gives a pretty clear error for that. ***The supervisor was unavailable or is not running*** I believe

**Comment by sam1el** [comment]
Also, if port `9631` is not available, this is configurable by the cookbook resource and can be reassigned in the `hab_sup` resource using the `listener` options. You would see the same error mentioned previously.

**Comment by collinmcneese** [comment]
If the supervisor is not running(service is stopped or disabled), this cookbook should be starting it during execution (confirmed on test instances just now), are you seeing different behavior with that @ericcalabretta ?

**Comment by ericcalabretta** [comment]
@collinmcneese The behavior was the Supervisor API crashed, causing the cookbook to fail. 

The Supervisor and the CLI was good, but we couldn't load/unload services without the API. Let me see if I can grab better error reporting. 

Good to hear we have some of these conditions already handled, this was a tough one to identify with all the moving parts.

**Comment by sam1el** [comment]
collin has a great point. if the supervisor is down, this should bring it up. if it isn't coming up. there could be a bad configuration

**Comment by sam1el** [comment]
the only way I can see to fix this is to make an api call to the local machines supervisor and if it doesn't respond. exit with a message. we would also need to verify if the service is already installed before them. I'm not sure it makes sense to do that.
