### ISSUE TITLE
Binlinking not reliably working via the hab_package resource.

### ISSUE THREAD

**Issue by mike10010100** [chef-cookbooks/habitat#231]
We're running into situations where packages that were previously installed on a machine are unable to be force binlinked by hab pkg installs via the hab_package resource.

For example, inside of a test kitchen, we have installed curl in centos via the package resource, but when we attempt to install core/curl via hab_package and set binlink to `:force`, it ends up erroring and claiming that it cannot overwrite it.

In other situations, there is no error, but we don't see the proper binlinking occurring in the target box.

Habitat version: hab 1.5.86/20200408002109
Habitat cookbook version: 2.0.2

**Comment by sam1el** [comment]
@mike10010100 could you please provide a bit more info like the error output? Since you are trying to install and binlink `curl` the error makes me think it doesn't like you trying to overwrite the systems builtin curl.

**Comment by fifthecho** [comment]
I think a better example that's part of our use case is we install our own version of `helm` and binlink it.

If we install a new version of `helm` and request binlinking, it isn't updating to the newer version. @mike10010100 can provide the actual error(s) (if any).

**Comment by sam1el** [comment]
normally when we see that error in habitat, it's a user permissions issue. Can you look at the `/hab` directory as well as `/bin/hab` to see what permissions are there? They would normally be owned by the hab user.

**Comment by sam1el** [comment]
If these are running in an effortless pattern, you should be able to see the stacktrace in the supervisor logs. otherwise, they would be in the normal chef-client stacktrace. Let me verify those directories.

**Comment by mike10010100** [comment]
Yeah these logs are being taken from syslog from an effortless pattern chef-client run. If there's physical logs being dumped somewhere, that would be super useful.

**Comment by sam1el** [comment]
sorry for the late reply. Can you look in `/hab/svc/<pkg_name>/cache`

**Comment by mike10010100** [comment]
So after some further investigation, it looks like binlinking was actually working, and the errors being thrown were a red herring. It turns out it was a PATH issue whereby packages were installed to /usr/local/bin, but hab pkgs were being binlinked to /bin. The user's PATH prioritized the former over the latter, and thus our confusion.

Thank you for the help, all!
