### ISSUE TITLE
manage and rotate the hab_sup logging 

### ISSUE THREAD

**Issue by mattray** [chef-cookbooks/habitat#250]
By default, the hab_sup resource is logging to /var/log/syslog and the /var/log/daemon.log and isn't rotating anything. After running automate and several habitat services for a month these files are 500+ megabytes each. Eventually this is going to bite someone.

**Comment by sam1el** [comment]
Log rotation isn't sometbjng that hab should be managing. Thats normally a confog management function at the os level. Im happy to add something if you have code to so. Otherwise, we don't normally dictate how an os manages the logs unless they are specifically writing a cookbook for it.

**Comment by collinmcneese** [comment]
Most organizations running Linux have some sort of logrotate policy to accomplish this, I agree that we should not be enforcing any logging changes when we are logging to standard syslog facilities.  Perhaps we could update the `README` instead indicating where logging is sent and if it is to standard locations then it should be indicated as a reference point -- trying to manage those standard syslog locations with this cookbook is a bit out of scope.

**Comment by sam1el** [comment]
This is decidedly on the customer's to manage. We cannot dictate when and how they choose to maintain their logs.
