### ISSUE TITLE
`shutdown_timeout` property for the `hab_service` resource always compares against the default value set by the package rather than the effective value for a service's `shutdown_timeout`.

### ISSUE THREAD

**Issue by patrick-baldridge** [chef-cookbooks/habitat#260]
`shutdown_timeout` property for the `hab_service` resource always compares against the default value set by the package rather than the effective value for a service's `shutdown_timeout`. If you provide a value different than the default value provided by the package for `shutdown_timeout`, the result is the resource updating on every converge due to the [comparison logic](https://github.com/chef-cookbooks/habitat/blob/master/resources/service.rb#L194-L195). Unfortunately I do not see the effective shutdown_timeout provided by the supervisor API, so I cannot provide a recommendation on how to resolve this, or able to provide a PR to fix. [I've opened an issue on the habitat repo](https://github.com/habitat-sh/habitat/issues/8084#issuecomment-787963909) asking where I could submit a feature request to expose the effective value for a service's `shutdown_timeout` by the supervisor API.

**Comment by patrick-baldridge** [comment]
A PR has been merged to the Habitat repo which addresses the issue of the supervisor http gateway data for a service only displaying the package's default shutdown_timeout value. Now the effective shutdown_timeout value will be shown. This should fix this issue once a new build of the hab packages are made and promoted to stable.
I will open a new issue that the cookbook is always passing the `--shutdown-timeout` flag when loading a service even when the `shutdown_timeout` property of the `hab_service` resource is not set. This effectively overrides any default value that has been set in the `plan.sh` for a package.

**Comment by sam1el** [comment]
Thank you! I will take a look at it asap and see if I can't implement a fix quickly
