### ISSUE TITLE
curl fails to download custom install script, downloads HTML instead

### ISSUE THREAD

**Issue by thompsonbrian** [chef-cookbooks/habitat#266]
We have a couple thousand nodes configured to use our own wrapper of this cookbook, which works on most of the nodes.  On one of them, we get the following error:

```
had an error: Mixlib::ShellOut::ShellCommandFailed: execute[installing with hab-install.sh] (/var/chef/cache/cookbooks/habitat/resources/install.rb line 123) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of bash /var/chef/cache/hab-install.sh ----
STDOUT: 
STDERR: /var/chef/cache/hab-install.sh: line 1: syntax error near unexpected token `newline'
/var/chef/cache/hab-install.sh: line 1: `<!DOCTYPE html>'
---- End output of bash /var/chef/cache/hab-install.sh ----
Ran bash /var/chef/cache/hab-install.sh returned 2
```

This usually happens when curl fails to download our install script.  I'm just curious if the habitat cookbook has curl as a dependency so it doesn't depend on the system-installed version of curl.

**Comment by sam1el** [comment]
It does not.  When creating the cookbook we wanted to leave out as many external dependencies as possible.

**Comment by thompsonbrian** [comment]
Thanks.  That makes sense.  Closing since that was my only question.
