### ISSUE TITLE
Add an option for adding binstubs

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/habitat#3]
I'd love to use this cookbook to install habitat packages that can be used without special paths or anything else. Basically I want to user to not know they're running a habitat package. It would be great if we could optionally create bin stubs in the provider.

**Comment by smith** [comment]
You can use `hab pkg binlink` to do that. Perhaps you could add an option in the resource like:

```ruby
habitat_package 'core/coreutils' do
  binlink %w[ ln ls ]
end
```

that would run `hab pkg binlink core/coreutils ln; hab pkg binlink core/coreutils ls` which would give you /usr/bin/l{n,s}.

**Comment by lamont-granquist** [comment]
binlinks should really go into the metadata of the package so that this looks more like `binlink "/usr/local/bin"` to tell it to wire up all the configured binlinks into /usr/local/bin.

i'm pretty certain right now you need to tell hab pkg one-by-one to install every bin you need which will complicate the API here a lot, and i think is pretty wrong.

**Comment by lamont-granquist** [comment]
i think hab by default also links into `/bin/ruby` or something similarly awful that should never, ever happen?

that default probably changes in hab the first time someone overwrite /bin/bash or something...

**Comment by smith** [comment]
@lamont-granquist could you please open an issue on habitat-sh/habitat describing how this should behave to not be awful?

Here's the help output from `hab pkg binlink`:

```
[24][default:/src:0]# hab pkg binlink --help
hab-pkg-binlink
Creates a symlink for a package binary in a common 'PATH' location

USAGE:
    hab pkg binlink [FLAGS] [OPTIONS] <PKG_IDENT> <BINARY>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -d, --dest <DEST_DIR>    Sets the destination directory (default: /bin)

ARGS:
    <PKG_IDENT>    A package identifier (ex: core/redis, core/busybox-static/1.42.2)
    <BINARY>       The command to symlink (ex: bash)
```

**Comment by lamont-granquist** [comment]
yes, that's mostly the whole plan behind this cookbook is to generate issues against habitat and go fix them...

right now i can't write that issue though because i don't know enough
