### ISSUE TITLE
what needs to get done in order to add these to core chef?

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/habitat#30]
what are we waiting for?

**Comment by lamont-granquist** [comment]
master of chef/chef is open for chef-13.0 development, and while we aren't blocked on including this in core chef in a minor rev, so we could do this at any time, it seems like chef 13.0 or 13.1 would get some nice shiney stuff into chef 13 people could talk about?

**Comment by smith** [comment]
I don't see anything stopping it. Some of the service stuff will change when new enhancements to the supervisor ship, but that won't be before Chef 13. +1 from me.

**Comment by thommay** [comment]
I'm 👍 on doing this soon.

**Comment by jtimberman** [comment]
With the changes to the `hab_service` and addition of `hab_sup` in version 0.4.0, is it time to revisit this?

**Comment by lamont-granquist** [comment]
yeah delivering and debugging Chef 13 and ChefDK 2.0 have been a bit of a mess though.  i suspect even after we ship ChefDK 2.0 that there'll be some fallout that needs fixing, and then we can get back to more forwards-looking software development.

**Comment by luisdavim** [comment]
Hi, any news on this?

**Comment by jtimberman** [comment]
The habitat core team is committed to maintaining compliance with semver. As such, 0.xx releases may have breaking changes. Once the habitat project reaches 1.0, we should get these resources into core Chef. Until then, there exists too much potential for backwards incompatibility for hab commandline options and other possible causes of breakage.
