### ISSUE TITLE
replace load_current_value with hab status

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/habitat#32]
Currently the `hab_service` resource uses the Habitat supervisor's API to get the service state. In Habitat 0.22.0, a new `hab sup status` command that will report the status of the given service names. At this time, the output is not [super friendly for machine consumption](https://github.com/habitat-sh/habitat/issues/2274). Chiefly, there are  two problems:

1. The output uses color escape sequences that can make parsing problematic
2. The output is an English sentence that means we have to use a regular expression to get the data we want

It is preferable that the output report the service name / fully qualified Habitat package identifier with its current state as two separate fields in a string that has a stable API so we don't have to update the `load_current_value` method again later.

Once this issue is resolved, we should use `hab sup status` to get the status of services in the supervisor.

**Comment by tas50** [comment]
I'd actually prefer to stick to the endpoint. Parsing out shellouts is problematic and probably slower.
