### ISSUE TITLE
issues since 0.26.0 release of Habitat

### ISSUE THREAD

**Issue by bixu** [chef-cookbooks/habitat#35]
Post-0.26.0, I see errors like this
```
Jul 15 11:26:18 c9a50834-6af8-cbc5-89f8-a12eb3cdaa83 hab[57270]: hab-sup(MN)[src/main.rs:112:42]: Supervisor must be run from 'hab-launch'
```
when using the cookbooks default Supervisor resource

**Comment by tas50** [comment]
I released a new 0.26 with some fixed for 0.26. I don't believe this particular issue is fixed, but you might want to give it a try. Package / service resources work again.
