### ISSUE TITLE
hab-sup lacks restart action on systemd

### ISSUE THREAD

**Issue by joshbrand** [chef-cookbooks/habitat#47]
### Cookbook version
`0.33.0`
### Chef-client version
`13.3.24`
### Platform Details
Any
### Scenario:
In some cases, for example, when adding a systemd override file, it's necessary to restart `hab-sup` within a cookbook

### Steps to Reproduce:
on a resource:
`notifies :restart, 'hab_sup[default]'`

### Expected Result:
`hab-sup` restarts

### Actual Result:
```
NoMethodError: undefined method `action_restart' for Custom resource habitat_sup_systemd from cookbook habitat
```

**Comment by sam1el** [comment]
Added ExecStop to the systemd service which add the restart function by default with systemd. Systemd now functioing as expected.
