### ISSUE TITLE
Is this a typo bug?

### ISSUE THREAD

**Issue by tevert** [chef-cookbooks/habitat#9]
The function parameter names do not match the usages within the function. Looks like a copy-paste bug.

https://github.com/chef-cookbooks/habitat/blob/master/libraries/provider_hab_package.rb#L71

**Comment by lamont-granquist** [comment]
yeah but don't use `:remove` yet, it literally scares the crap out of me.

**Comment by jtimberman** [comment]
I opened an issue on the habitat project. If such a sub command is deemed appropriate, and then later added to `hab` CLI, we will be able to implement the `remove` action safely in this cookbook's resource.

**Comment by jtimberman** [comment]
PR and issue in the habitat repo: 

* https://github.com/habitat-sh/habitat/pull/3717
* https://github.com/habitat-sh/habitat/issues/3586#issuecomment-337503557
