### ISSUE TITLE
Support on-prem builder in `hab_sup` resource

### ISSUE THREAD

**Issue by Atalanta** [chef-cookbooks/habitat#94]
### Cookbook version

0.55.0

### Chef-client version

- 14.1.12
- 13.8.5

### Platform Details

- CentOS 7.x

### Scenario:

We use on-premesis Builder, and have no outbound access to upstream resources.  The `hab_sup` resource includes a `hab_package` resource to ensure `core/hab-sup` is installed.  However, this does not support `:bldr_url`, so and `hap_sup` resources time out.

### Steps to Reproduce:

- Deny outbound access to *.habitat.sh
- On a machine where you've already installed Habitat, try to converge:

```ruby
hab_sup 'default'
```
### Expected Result:

The converge will time out, unable to reach https://willem.habitat.sh

### Actual Result:

The converge will time out, unable to reach https://willem.habitat.sh

### Proposed fix:

https://github.com/chef-cookbooks/habitat/pull/93

Now you can do:

```ruby
hab_sup 'default' do
  bldr_url 'http://your.private.bldr'
end
```

And the converge will succeed.

**Comment by jonlives** [comment]
PR #93 was merged and released with version 0.56.1 of this cookbook, so closing off this issue now.
